export const handleMainTabData = value => dispatch => dispatch({ type: 'MAIN_TAB_DATA', value })
export const handleSubTabData = value => dispatch => dispatch({ type: 'SUB_TAB_DATA', value })
export const handleData = value => dispatch => dispatch({ type: 'TAB_DATA', value })
export const handlefieldsData = value => dispatch => dispatch({ type: 'FIELD_SETS', value })
export const handleExistingData = value => dispatch => dispatch({ type: 'ISEXISTDATA', value })